# Generated by Django 4.1 on 2023-04-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ColumnStatisticsModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mean_val", models.FloatField()),
                ("max_val", models.FloatField()),
                ("min_val", models.FloatField()),
                ("std_val", models.FloatField()),
                ("median_val", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SourceFileModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=1000)),
                ("file_src", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="TeamStatisticsModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=1000)),
                (
                    "merge_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_time",
                        to="story_tracking.columnstatisticsmodel",
                    ),
                ),
                (
                    "review_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_time",
                        to="story_tracking.columnstatisticsmodel",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="story_tracking.sourcefilemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryPRDataModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("team", models.CharField(max_length=1000)),
                ("review_time", models.FloatField()),
                ("merge_time", models.FloatField()),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="story_tracking.sourcefilemodel",
                    ),
                ),
            ],
        ),
    ]
